version: "2"
checks:
  method-lines:
    config:
      threshold: 100
  method-complexity:
    config:
      threshold: 10
  similar-code:
    config:
      threshold: 65
  identical-code:
    config:
      threshold: 65
exclude_patterns:
  - "src/**/*.test.ts"
  - "src/**/*.test.tsx"
  - "*config*"
  - "test/**/__fixtures__"
  - "theme"
  - "mashup-example"
