env:
  browser: true
  es2021: true
extends:
  - airbnb
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - prettier
rules:
  import/no-extraneous-dependencies: 0
  no-use-before-define: 0
  semi: 2
  quotes: [2, 'single']
overrides:
  - files:
    - src/**/*.tsx
    - src/**/*.ts
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: './tsconfig.json'
      ecmaFeatures:
        jsx: true
        ecmaVersion: 2018
        sourceType: module
    plugins:
      - react
      - '@typescript-eslint'
    extends:
      - 'plugin:@typescript-eslint/eslint-recommended'
      - 'plugin:@typescript-eslint/recommended'
      - airbnb-typescript
      - prettier
    rules:
      import/no-extraneous-dependencies: 0
      semi: 2
      quotes: [2, 'single']
      react/jsx-indent-props: 2

  # Unit test files
  - files:
      - src/**/__tests__/*.test.ts
      - src/**/__tests__/*.test.tsx
    env:
      jest: true
