export default () => ({
  type: "sn-pivot-table",
  genericObjects: [
    {
      getLayout: {
        qInfo: {
          qId: "PytkXF",
          qType: "sn-pivot-table",
        },
        qMeta: {
          privileges: ["read"],
        },
        qSelectionInfo: {},
        qHyperCube: {
          qSize: {
            qcx: 2,
            qcy: 73819,
          },
          qDimensionInfo: [
            {
              qFallbackTitle: "Customer",
              qApprMaxGlyphCount: 36,
              qCardinal: 347,
              qSortIndicator: "A",
              qGroupFallbackTitles: ["Customer"],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 347,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ["$text"],
              qDimensionType: "D",
              qGrouping: "N",
              qNumFormat: {
                qType: "U",
                qnDec: 0,
                qUseThou: 0,
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ["Customer"],
              qMin: "NaN",
              qMax: "NaN",
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 347,
                qHypercubeCardinal: 347,
                qAllValuesCardinal: -1,
              },
              qLibraryId: "f2a6777e-8e09-438d-bd3e-3faa6b4bfeef",
              title: "Customer",
              autoSort: true,
              cId: "wzQRe",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
            },
            {
              qFallbackTitle: "Basket Product Line Desc",
              qApprMaxGlyphCount: 5,
              qCardinal: 2,
              qSortIndicator: "A",
              qGroupFallbackTitles: ["Basket Product Line Desc"],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 2,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ["$ascii", "$text"],
              qDimensionType: "D",
              qGrouping: "N",
              qNumFormat: {
                qType: "U",
                qnDec: 0,
                qUseThou: 0,
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ["Basket Product Line Desc"],
              qMin: "NaN",
              qMax: "NaN",
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 2,
                qHypercubeCardinal: 3,
                qAllValuesCardinal: -1,
              },
              qLibraryId: "4a4fe6fa-4f93-4ca8-b486-1b03cad6c9e5",
              title: "Basket Product Line Desc",
              autoSort: true,
              cId: "yxgsU",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
            },
            {
              qFallbackTitle: "Basket Product Group Desc",
              qApprMaxGlyphCount: 19,
              qCardinal: 17,
              qSortIndicator: "A",
              qGroupFallbackTitles: ["Basket Product Group Desc"],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 17,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ["$ascii", "$text"],
              qDimensionType: "D",
              qGrouping: "N",
              qNumFormat: {
                qType: "U",
                qnDec: 0,
                qUseThou: 0,
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ["Basket Product Group Desc"],
              qMin: "NaN",
              qMax: "NaN",
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 17,
                qHypercubeCardinal: 18,
                qAllValuesCardinal: -1,
              },
              qLibraryId: "3b8d4270-9fc9-47dc-b6a5-09887644b996",
              title: "Basket Product Group Desc",
              autoSort: true,
              cId: "DWcsDs",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
            },
            {
              qFallbackTitle: "Basket Product Desc",
              qApprMaxGlyphCount: 37,
              qCardinal: 827,
              qSortIndicator: "A",
              qGroupFallbackTitles: ["Basket Product Desc"],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 827,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ["$ascii", "$text"],
              qDimensionType: "D",
              qGrouping: "N",
              qNumFormat: {
                qType: "U",
                qnDec: 0,
                qUseThou: 0,
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ["Basket Item Desc"],
              qMin: "NaN",
              qMax: "NaN",
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 827,
                qHypercubeCardinal: 828,
                qAllValuesCardinal: -1,
              },
              qLibraryId: "YkpKr",
              title: "Basket Product Desc",
              autoSort: true,
              cId: "JYeJL",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
            },
          ],
          qMeasureInfo: [
            {
              qFallbackTitle: "Avg Sales",
              qApprMaxGlyphCount: 11,
              qCardinal: 0,
              qSortIndicator: "D",
              qNumFormat: {
                qType: "R",
                qnDec: 0,
                qUseThou: 0,
                qFmt: "########",
                qDec: ".",
                qThou: ",",
              },
              qMin: -6028.650000000001,
              qMax: 226098.28625,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qLibraryId: "LvjWKp",
              qTrendLines: [],
              autoSort: true,
              cId: "stjQfQ",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
              quarantine: {
                qNumFormat: {},
                isCustomFormatted: false,
              },
            },
            {
              qFallbackTitle: "Actual Amount",
              qApprMaxGlyphCount: 11,
              qCardinal: 0,
              qSortIndicator: "D",
              qNumFormat: {
                qType: "U",
                qnDec: 0,
                qUseThou: 0,
              },
              qMin: -849.12,
              qMax: 11434394.96,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qLibraryId: "vDhvSum",
              qTrendLines: [],
              coloring: {},
              autoSort: true,
              cId: "TDsUJK",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
              quarantine: {
                qNumFormat: {},
                isCustomFormatted: false,
              },
            },
          ],
          qEffectiveInterColumnSortOrder: [0, 1, 2, 3, -1],
          qGrandTotalRow: [],
          qDataPages: [],
          qPivotDataPages: [
            {
              qLeft: [
                {
                  qText: "A-ARVIN Laser Resources",
                  qElemNo: 293,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [
                    {
                      qText: "Drink",
                      qElemNo: 1,
                      qValue: "NaN",
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qText: "Beverages",
                          qElemNo: 7,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "BBB Best Decaf Coffee",
                              qElemNo: 773,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Excellent Orange Juice",
                              qElemNo: 483,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Washington Diet Cola",
                              qElemNo: 220,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                        {
                          qText: "Canned Foods",
                          qElemNo: 2,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "Better Rice Soup",
                              qElemNo: 439,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Blue Label Fancy Canned Oysters",
                              qElemNo: 8,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Just Right Turkey Noodle Soup",
                              qElemNo: 115,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                        {
                          qText: "Dairy",
                          qElemNo: 5,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "Even Better Chocolate Milk",
                              qElemNo: 698,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Even Better Low Fat String Cheese",
                              qElemNo: 447,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Even Better Mild Cheddar Cheese",
                              qElemNo: 76,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Even Better Sharp Cheddar Cheese",
                              qElemNo: 245,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Gorilla Havarti Cheese",
                              qElemNo: 56,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                        {
                          qText: "Deli",
                          qElemNo: 3,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "Cutting Edge Low Fat Bologna",
                              qElemNo: 320,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Cutting Edge Turkey Hot Dogs",
                              qElemNo: 303,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Red Spade Beef Bologna",
                              qElemNo: 33,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                        {
                          qText: "Frozen Foods",
                          qElemNo: 0,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "Big Time Beef TV Dinner",
                              qElemNo: 290,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Big Time Frozen Pancakes",
                              qElemNo: 671,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Golden Frozen Chicken Thighs",
                              qElemNo: 186,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                        {
                          qText: "Produce",
                          qElemNo: 1,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "Ebony Almonds",
                              qElemNo: 334,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Ebony Plums",
                              qElemNo: 302,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Ebony Prepared Salad",
                              qElemNo: 1,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "High Top Macintosh Apples",
                              qElemNo: 130,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "High Top Red Delcious Apples",
                              qElemNo: 766,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Tell Tale Firm Tofu",
                              qElemNo: 178,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                        {
                          qText: "Snack Foods",
                          qElemNo: 6,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "Fast Low Fat Cookies",
                              qElemNo: 487,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      qText: "Food",
                      qElemNo: 0,
                      qValue: "NaN",
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qText: "Beverages",
                          qElemNo: 7,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "BBB Best Decaf Coffee",
                              qElemNo: 773,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Excellent Orange Juice",
                              qElemNo: 483,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Washington Diet Cola",
                              qElemNo: 220,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                        {
                          qText: "Canned Foods",
                          qElemNo: 2,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "Better Rice Soup",
                              qElemNo: 439,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Blue Label Fancy Canned Oysters",
                              qElemNo: 8,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Just Right Turkey Noodle Soup",
                              qElemNo: 115,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                        {
                          qText: "Dairy",
                          qElemNo: 5,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "Even Better Chocolate Milk",
                              qElemNo: 698,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Even Better Low Fat String Cheese",
                              qElemNo: 447,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Even Better Mild Cheddar Cheese",
                              qElemNo: 76,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Even Better Sharp Cheddar Cheese",
                              qElemNo: 245,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Gorilla Havarti Cheese",
                              qElemNo: 56,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                        {
                          qText: "Deli",
                          qElemNo: 3,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "Cutting Edge Low Fat Bologna",
                              qElemNo: 320,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Cutting Edge Turkey Hot Dogs",
                              qElemNo: 303,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Red Spade Beef Bologna",
                              qElemNo: 33,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                        {
                          qText: "Frozen Foods",
                          qElemNo: 0,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "Big Time Beef TV Dinner",
                              qElemNo: 290,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Big Time Frozen Pancakes",
                              qElemNo: 671,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Golden Frozen Chicken Thighs",
                              qElemNo: 186,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                        {
                          qText: "Produce",
                          qElemNo: 1,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "Ebony Almonds",
                              qElemNo: 334,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Ebony Plums",
                              qElemNo: 302,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Ebony Prepared Salad",
                              qElemNo: 1,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "High Top Macintosh Apples",
                              qElemNo: 130,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "High Top Red Delcious Apples",
                              qElemNo: 766,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                            {
                              qText: "Tell Tale Firm Tofu",
                              qElemNo: 178,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                        {
                          qText: "Snack Foods",
                          qElemNo: 6,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "Fast Low Fat Cookies",
                              qElemNo: 487,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  qText: "A&R Partners",
                  qElemNo: 159,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 15,
                  qSubNodes: [
                    {
                      qText: "-",
                      qElemNo: -2,
                      qValue: "NaN",
                      qType: "U",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qText: "-",
                          qElemNo: -2,
                          qValue: "NaN",
                          qType: "U",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [
                            {
                              qText: "-",
                              qElemNo: -2,
                              qValue: "NaN",
                              qType: "U",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      qText: "Drink",
                      qElemNo: 1,
                      qValue: "NaN",
                      qType: "N",
                      qUp: 0,
                      qDown: 7,
                      qSubNodes: [
                        {
                          qText: "Baking Goods",
                          qElemNo: 8,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 1,
                          qSubNodes: [
                            {
                              qText: "BBB Best Vegetable Oil",
                              qElemNo: 373,
                              qValue: "NaN",
                              qType: "N",
                              qUp: 0,
                              qDown: 0,
                              qSubNodes: [],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
              qTop: [
                {
                  qText: "Avg Sales",
                  qElemNo: 0,
                  qValue: "NaN",
                  qType: "P",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Actual Amount",
                  qElemNo: 1,
                  qValue: "NaN",
                  qType: "P",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
              ],
              qData: [
                [
                  {
                    qText: "6.61",
                    qNum: 6.61,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "6.61",
                    qNum: 6.61,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "16.596667",
                    qNum: 16.596666666666668,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "13.61",
                    qNum: 13.61,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "17.51",
                    qNum: 17.51,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "0",
                    qNum: 0,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "787.31",
                    qNum: 787.3100000000001,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "13.61",
                    qNum: 13.61,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "1280.0233",
                    qNum: 1280.0233333333333,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "353.42273",
                    qNum: 353.42272727272734,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "117.142",
                    qNum: 117.14200000000001,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "122.31",
                    qNum: 122.31,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "289.73667",
                    qNum: 289.7366666666667,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "39.733333",
                    qNum: 39.733333333333334,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "75.41",
                    qNum: 75.41,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "99.636667",
                    qNum: 99.63666666666667,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "0",
                    qNum: 0,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "13.42",
                    qNum: 13.42,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "117.142",
                    qNum: 117.14200000000001,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "573.37",
                    qNum: 573.37,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "0",
                    qNum: 0,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "0",
                    qNum: 0,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "43.54",
                    qNum: 43.54,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "284.51727",
                    qNum: 284.51727272727277,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "6.61",
                    qNum: 6.61,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "6.61",
                    qNum: 6.61,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "16.596667",
                    qNum: 16.596666666666668,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "13.61",
                    qNum: 13.61,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "17.51",
                    qNum: 17.51,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "0",
                    qNum: 0,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "787.31",
                    qNum: 787.3100000000001,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "13.61",
                    qNum: 13.61,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "1280.0233",
                    qNum: 1280.0233333333333,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "353.42273",
                    qNum: 353.42272727272734,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "117.142",
                    qNum: 117.14200000000001,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "122.31",
                    qNum: 122.31,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "289.73667",
                    qNum: 289.7366666666667,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "39.733333",
                    qNum: 39.733333333333334,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "75.41",
                    qNum: 75.41,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "99.636667",
                    qNum: 99.63666666666667,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "0",
                    qNum: 0,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "13.42",
                    qNum: 13.42,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "117.142",
                    qNum: 117.14200000000001,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "573.37",
                    qNum: 573.37,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "0",
                    qNum: 0,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "0",
                    qNum: 0,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "43.54",
                    qNum: 43.54,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "284.51727",
                    qNum: 284.51727272727277,
                    qType: "V",
                  },
                  {
                    qText: "10850.3",
                    qNum: 10850.300000000003,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "17099.07",
                    qNum: 17099.07,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "21.21",
                    qNum: 21.21,
                    qType: "V",
                  },
                  {
                    qText: "17099.07",
                    qNum: 17099.07,
                    qType: "V",
                  },
                ],
              ],
              qArea: {
                qLeft: 0,
                qTop: 0,
                qWidth: 2,
                qHeight: 50,
              },
            },
          ],
          qStackedDataPages: [],
          qMode: "P",
          qNoOfLeftDims: 4,
          qTreeNodesOnDim: [],
          qColumnOrder: [],
        },
        search: {
          sorting: "auto",
        },
        showTitles: true,
        title: "",
        subtitle: "4 rows, pseudo dim as column. Exceed max left grid width.",
        footnote: "",
        disableNavMenu: false,
        showDetails: true,
        showDetailsExpression: false,
        components: [],
        nullValueRepresentation: {
          text: "-",
        },
        visualization: "sn-pivot-table",
        version: "2.3.0",
        extensionMeta: {
          translationKey: "",
          icon: "puzzle",
          iconChar: "puzzle",
          isLibraryItem: true,
          visible: true,
          IconDefinition: {},
          name: "sn-pivot-table",
          description: "Pivot table supernova",
          template: "sn-pivot-table",
          iconPath:
            "M14.5,9 L13,9 L13,3.3 C13,3.1 12.9,3 12.7,3 L8,3 L8,1.5 C8,0.7 7.3,0 6.5,0 C5.7,0 5,0.7 5,1.5 L5,3 L0.3,3 C0.1,3 0,3.1 0,3.3 L0,9 L1.5,9 C2.3,9 3,9.7 3,10.5 C3,11.3 2.3,12 1.5,12 L0,12 L0,15.7 C0,15.9 0.1,16 0.3,16 L5,16 L5,14.5 C5,13.7 5.7,13 6.5,13 C7.3,13 8,13.7 8,14.5 L8,16 L12.7,16 C12.9,16 13,15.9 13,15.7 L13,12 L14.5,12 C15.3,12 16,11.3 16,10.5 C16,9.7 15.3,9 14.5,9 Z",
          isThirdParty: true,
          id: "rmQctFcQtWrx-gPyk6gzUvfnphijKOxY",
          tenantId: "So2tYBBh-SeC2uqq2ghwvPxTRS9ca45i",
          userId: "Tc_Xcu0ACCRJHvXCacSY0_VWrOZIqP0C",
          type: "visualization",
          qextFilename: "sn-pivot-table",
          qextVersion: "2.4.0",
          loadpath: "sn-pivot-table",
          version: "56.0.0",
          author: "QlikTech International AB",
          tags: [],
          checksum: null,
          bundled: false,
          supernova: true,
          file: {
            contentType: "application/zip",
            contentLength: 1252280,
            md5: "0cfe6bc70ecb73fed6e32eae923b973d",
            fileId: "fZgQ8eKieiuvW6LXsXhjMMgHRRn_M4xP",
            originalname: "sn-pivot-table-ext.zip",
          },
          createdAt: "2023-10-06T12:44:39.924Z",
          updatedAt: "2023-11-16T10:07:02.333Z",
          cloud: true,
        },
        appId: "1aac3e7b-5681-43c3-8516-8269ba82c0d2",
      },
      getEffectiveProperties: {
        qHyperCubeDef: {},
      },
    },
  ],
});
