export default () => ({
  type: "sn-pivot-table",
  genericObjects: [
    {
      getLayout: {
        qInfo: {
          qId: "bccaa54e-0884-46b3-994d-daf9274561ec",
          qType: "embeddedsnapshot",
        },
        qMeta: {
          privileges: ["read", "update", "delete", "exportdata"],
        },
        qBookmark: {
          qStateData: [
            {
              qStateName: "$",
              qFieldItems: [],
            },
          ],
          qUtcModifyTime: 45057.476631944446,
          qVariableItems: [],
          qPatches: [],
        },
        qFieldInfos: [],
        creationDate: "2023-05-11T11:26:21.181Z",
        qSelectionInfo: {},
        qHyperCube: {
          qSize: {
            qcx: 18,
            qcy: 3,
          },
          qDimensionInfo: [
            {
              qFallbackTitle: "Dim1",
              qApprMaxGlyphCount: 1,
              qCardinal: 3,
              qSortIndicator: "A",
              qGroupFallbackTitles: ["Dim1"],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 3,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ["$ascii", "$text"],
              qDimensionType: "D",
              qGrouping: "N",
              qNumFormat: {
                qType: "U",
                qnDec: 0,
                qUseThou: 0,
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ["Dim1"],
              qMin: "NaN",
              qMax: "NaN",
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 3,
                qHypercubeCardinal: 3,
                qAllValuesCardinal: -1,
              },
              autoSort: true,
              cId: "dKhSYX",
            },
            {
              qFallbackTitle: "Dim2",
              qApprMaxGlyphCount: 1,
              qCardinal: 6,
              qSortIndicator: "A",
              qGroupFallbackTitles: ["Dim2"],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 6,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ["$ascii", "$text"],
              qDimensionType: "D",
              qGrouping: "N",
              qNumFormat: {
                qType: "U",
                qnDec: 0,
                qUseThou: 0,
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ["Dim2"],
              qMin: "NaN",
              qMax: "NaN",
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 6,
                qHypercubeCardinal: 6,
                qAllValuesCardinal: -1,
              },
              autoSort: true,
              cId: "fUQZHYq",
            },
          ],
          qMeasureInfo: [
            {
              qFallbackTitle: "Sum(Expression1)",
              qApprMaxGlyphCount: 5,
              qCardinal: 0,
              qSortIndicator: "D",
              qNumFormat: {
                qType: "I",
                qnDec: 0,
                qUseThou: 1,
                qFmt: "###0",
                qDec: ".",
              },
              qMin: 7502,
              qMax: 82027,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qTrendLines: [],
              autoSort: true,
              cId: "kvsGaG",
            },
            {
              qFallbackTitle: "Sum(Expression2)",
              qApprMaxGlyphCount: 3,
              qCardinal: 0,
              qSortIndicator: "D",
              qNumFormat: {
                qType: "I",
                qnDec: 0,
                qUseThou: 1,
                qFmt: "###0",
                qDec: ".",
              },
              qMin: 38,
              qMax: 797,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qTrendLines: [],
              autoSort: true,
              cId: "fbpmGLq",
            },
            {
              qFallbackTitle: "Sum(Expression3)",
              qApprMaxGlyphCount: 9,
              qCardinal: 0,
              qSortIndicator: "D",
              qNumFormat: {
                qType: "F",
                qnDec: 5,
                qUseThou: 1,
                qFmt: "###0.00000",
                qDec: ".",
              },
              qMin: 15.795929999999998,
              qMax: 161.11037999999994,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qTrendLines: [],
              autoSort: true,
              cId: "bDwYsV",
            },
          ],
          qEffectiveInterColumnSortOrder: [0, 1, -1],
          qGrandTotalRow: [],
          qDataPages: [],
          qPivotDataPages: [
            {
              qLeft: [
                {
                  qText: "A",
                  qElemNo: 2,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "B",
                  qElemNo: 1,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "C",
                  qElemNo: 0,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
              ],
              qTop: [
                {
                  qText: "a",
                  qElemNo: 3,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [
                    {
                      qText: "Sum(Expression1)",
                      qElemNo: 0,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                    {
                      qText: "Sum(Expression2)",
                      qElemNo: 1,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                    {
                      qText: "Sum(Expression3)",
                      qElemNo: 2,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                  ],
                },
                {
                  qText: "b",
                  qElemNo: 5,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [
                    {
                      qText: "Sum(Expression1)",
                      qElemNo: 0,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                    {
                      qText: "Sum(Expression2)",
                      qElemNo: 1,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                    {
                      qText: "Sum(Expression3)",
                      qElemNo: 2,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                  ],
                },
                {
                  qText: "c",
                  qElemNo: 2,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [
                    {
                      qText: "Sum(Expression1)",
                      qElemNo: 0,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                    {
                      qText: "Sum(Expression2)",
                      qElemNo: 1,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                    {
                      qText: "Sum(Expression3)",
                      qElemNo: 2,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                  ],
                },
                {
                  qText: "d",
                  qElemNo: 4,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [
                    {
                      qText: "Sum(Expression1)",
                      qElemNo: 0,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                    {
                      qText: "Sum(Expression2)",
                      qElemNo: 1,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                    {
                      qText: "Sum(Expression3)",
                      qElemNo: 2,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                  ],
                },
                {
                  qText: "e",
                  qElemNo: 1,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [
                    {
                      qText: "Sum(Expression1)",
                      qElemNo: 0,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                    {
                      qText: "Sum(Expression2)",
                      qElemNo: 1,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                    {
                      qText: "Sum(Expression3)",
                      qElemNo: 2,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                  ],
                },
                {
                  qText: "f",
                  qElemNo: 0,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [
                    {
                      qText: "Sum(Expression1)",
                      qElemNo: 0,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                    {
                      qText: "Sum(Expression2)",
                      qElemNo: 1,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                    {
                      qText: "Sum(Expression3)",
                      qElemNo: 2,
                      qValue: "NaN",
                      qType: "P",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                  ],
                },
              ],
              qData: [
                [
                  {
                    qText: "7502",
                    qNum: 7502,
                    qType: "V",
                  },
                  {
                    qText: "38",
                    qNum: 38,
                    qType: "V",
                  },
                  {
                    qText: "15.79593",
                    qNum: 15.795929999999998,
                    qType: "V",
                  },
                  {
                    qText: "24466",
                    qNum: 24466,
                    qType: "V",
                  },
                  {
                    qText: "186",
                    qNum: 186,
                    qType: "V",
                  },
                  {
                    qText: "43.94730",
                    qNum: 43.94729999999997,
                    qType: "V",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                ],
                [
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "32223",
                    qNum: 32223,
                    qType: "V",
                  },
                  {
                    qText: "256",
                    qNum: 256,
                    qType: "V",
                  },
                  {
                    qText: "67.31297",
                    qNum: 67.31297,
                    qType: "V",
                  },
                  {
                    qText: "51527",
                    qNum: 51527,
                    qType: "V",
                  },
                  {
                    qText: "547",
                    qNum: 547,
                    qType: "V",
                  },
                  {
                    qText: "109.31130",
                    qNum: 109.31129999999996,
                    qType: "V",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                ],
                [
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "62551",
                    qNum: 62551,
                    qType: "V",
                  },
                  {
                    qText: "594",
                    qNum: 594,
                    qType: "V",
                  },
                  {
                    qText: "130.32919",
                    qNum: 130.32919,
                    qType: "V",
                  },
                  {
                    qText: "82027",
                    qNum: 82027,
                    qType: "V",
                  },
                  {
                    qText: "797",
                    qNum: 797,
                    qType: "V",
                  },
                  {
                    qText: "161.11038",
                    qNum: 161.11037999999994,
                    qType: "V",
                  },
                ],
              ],
              qArea: {
                qLeft: 0,
                qTop: 0,
                qWidth: 18,
                qHeight: 3,
              },
            },
          ],
          qStackedDataPages: [],
          qMode: "P",
          qNoOfLeftDims: 1,
          qTreeNodesOnDim: [],
          qColumnOrder: [],
        },
        search: {
          sorting: "auto",
        },
        showTitles: true,
        title: "Scenario 2",
        subtitle: "",
        footnote: "",
        disableNavMenu: false,
        showDetails: true,
        showDetailsExpression: false,
        components: [],
        nullValueRepresentation: {
          text: "-",
        },
        visualization: "sn-pivot-table",
        version: "2.0.0-alpha.1",
        extensionMeta: {
          translationKey: "",
          icon: "puzzle",
          iconChar: "puzzle",
          isLibraryItem: true,
          visible: true,
          name: "sn-pivot-table",
          description: "Pivot table supernova",
          template: "sn-pivot-table",
          iconPath:
            "M14.5,9 L13,9 L13,3.3 C13,3.1 12.9,3 12.7,3 L8,3 L8,1.5 C8,0.7 7.3,0 6.5,0 C5.7,0 5,0.7 5,1.5 L5,3 L0.3,3 C0.1,3 0,3.1 0,3.3 L0,9 L1.5,9 C2.3,9 3,9.7 3,10.5 C3,11.3 2.3,12 1.5,12 L0,12 L0,15.7 C0,15.9 0.1,16 0.3,16 L5,16 L5,14.5 C5,13.7 5.7,13 6.5,13 C7.3,13 8,13.7 8,14.5 L8,16 L12.7,16 C12.9,16 13,15.9 13,15.7 L13,12 L14.5,12 C15.3,12 16,11.3 16,10.5 C16,9.7 15.3,9 14.5,9 Z",
          isThirdParty: true,
          version: "2.0.0-alpha.1",
          author: "QlikTech International AB",
          type: "visualization",
          supernova: true,
        },
        snapshotData: {
          object: {
            size: {
              w: 760.8333129882812,
              h: 341.66668701171875,
            },
          },
          rtl: false,
          content: {
            qPivotDataPages: [
              {
                qLeft: [
                  {
                    qText: "A",
                    qElemNo: 2,
                    qValue: "NaN",
                    qType: "N",
                    qUp: 0,
                    qDown: 0,
                    qSubNodes: [],
                  },
                  {
                    qText: "B",
                    qElemNo: 1,
                    qValue: "NaN",
                    qType: "N",
                    qUp: 0,
                    qDown: 0,
                    qSubNodes: [],
                  },
                  {
                    qText: "C",
                    qElemNo: 0,
                    qValue: "NaN",
                    qType: "N",
                    qUp: 0,
                    qDown: 0,
                    qSubNodes: [],
                  },
                ],
                qTop: [
                  {
                    qText: "a",
                    qElemNo: 3,
                    qValue: "NaN",
                    qType: "N",
                    qUp: 0,
                    qDown: 0,
                    qSubNodes: [
                      {
                        qText: "Sum(Expression1)",
                        qElemNo: 0,
                        qValue: "NaN",
                        qType: "P",
                        qUp: 0,
                        qDown: 0,
                        qSubNodes: [],
                      },
                      {
                        qText: "Sum(Expression2)",
                        qElemNo: 1,
                        qValue: "NaN",
                        qType: "P",
                        qUp: 0,
                        qDown: 0,
                        qSubNodes: [],
                      },
                      {
                        qText: "Sum(Expression3)",
                        qElemNo: 2,
                        qValue: "NaN",
                        qType: "P",
                        qUp: 0,
                        qDown: 0,
                        qSubNodes: [],
                      },
                    ],
                  },
                  {
                    qText: "b",
                    qElemNo: 5,
                    qValue: "NaN",
                    qType: "N",
                    qUp: 0,
                    qDown: 0,
                    qSubNodes: [
                      {
                        qText: "Sum(Expression1)",
                        qElemNo: 0,
                        qValue: "NaN",
                        qType: "P",
                        qUp: 0,
                        qDown: 0,
                        qSubNodes: [],
                      },
                      {
                        qText: "Sum(Expression2)",
                        qElemNo: 1,
                        qValue: "NaN",
                        qType: "P",
                        qUp: 0,
                        qDown: 0,
                        qSubNodes: [],
                      },
                      {
                        qText: "Sum(Expression3)",
                        qElemNo: 2,
                        qValue: "NaN",
                        qType: "P",
                        qUp: 0,
                        qDown: 0,
                        qSubNodes: [],
                      },
                    ],
                  },
                  {
                    qText: "c",
                    qElemNo: 2,
                    qValue: "NaN",
                    qType: "N",
                    qUp: 0,
                    qDown: 2,
                    qSubNodes: [
                      {
                        qText: "Sum(Expression1)",
                        qElemNo: 0,
                        qValue: "NaN",
                        qType: "P",
                        qUp: 0,
                        qDown: 0,
                        qSubNodes: [],
                      },
                    ],
                  },
                ],
                qData: [
                  [
                    {
                      qText: "7502",
                      qNum: 7502,
                      qType: "V",
                    },
                    {
                      qText: "38",
                      qNum: 38,
                      qType: "V",
                    },
                    {
                      qText: "15.79593",
                      qNum: 15.795929999999998,
                      qType: "V",
                    },
                    {
                      qText: "24466",
                      qNum: 24466,
                      qType: "V",
                    },
                    {
                      qText: "186",
                      qNum: 186,
                      qType: "V",
                    },
                    {
                      qText: "43.94730",
                      qNum: 43.94729999999997,
                      qType: "V",
                    },
                    {
                      qText: "-",
                      qNum: "NaN",
                      qType: "U",
                    },
                  ],
                  [
                    {
                      qText: "-",
                      qNum: "NaN",
                      qType: "U",
                    },
                    {
                      qText: "-",
                      qNum: "NaN",
                      qType: "U",
                    },
                    {
                      qText: "-",
                      qNum: "NaN",
                      qType: "U",
                    },
                    {
                      qText: "-",
                      qNum: "NaN",
                      qType: "U",
                    },
                    {
                      qText: "-",
                      qNum: "NaN",
                      qType: "U",
                    },
                    {
                      qText: "-",
                      qNum: "NaN",
                      qType: "U",
                    },
                    {
                      qText: "32223",
                      qNum: 32223,
                      qType: "V",
                    },
                  ],
                  [
                    {
                      qText: "-",
                      qNum: "NaN",
                      qType: "U",
                    },
                    {
                      qText: "-",
                      qNum: "NaN",
                      qType: "U",
                    },
                    {
                      qText: "-",
                      qNum: "NaN",
                      qType: "U",
                    },
                    {
                      qText: "-",
                      qNum: "NaN",
                      qType: "U",
                    },
                    {
                      qText: "-",
                      qNum: "NaN",
                      qType: "U",
                    },
                    {
                      qText: "-",
                      qNum: "NaN",
                      qType: "U",
                    },
                    {
                      qText: "-",
                      qNum: "NaN",
                      qType: "U",
                    },
                  ],
                ],
                qArea: {
                  qLeft: 0,
                  qTop: 0,
                  qWidth: 7,
                  qHeight: 3,
                },
              },
            ],
          },
          parent: {
            h: 1204,
            w: 1470,
          },
        },
        visualizationType: "sn-pivot-table",
        sourceObjectId: "kmbWhKZ",
        sheetId: "46228077-13df-48b7-8030-39a17b6c4702",
        timestamp: 1683804381168,
        isClone: false,
        supportExport: true,
      },
    },
  ],
});
