export default () => ({
  type: "sn-pivot-table",
  genericObjects: [
    {
      getLayout: {
        qInfo: {
          qId: "1695275938828",
          qType: "sn-pivot-table",
        },
        qMeta: {
          privileges: ["read", "update", "delete"],
        },
        qSelectionInfo: {},
        visualization: "sn-pivot-table",
        version: "2.1.0",
        showTitles: true,
        qHyperCube: {
          qSize: {
            qcx: 1,
            qcy: 20000,
          },
          qDimensionInfo: [
            {
              qFallbackTitle: "Product",
              qApprMaxGlyphCount: 48,
              qCardinal: 7942,
              qSortIndicator: "A",
              qGroupFallbackTitles: ["Product"],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 7942,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ["$key", "$ascii", "$text"],
              qDimensionType: "D",
              qGrouping: "N",
              qNumFormat: {
                qType: "U",
                qnDec: 0,
                qUseThou: 0,
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ["Line Desc 1"],
              qMin: "NaN",
              qMax: "NaN",
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 7942,
                qHypercubeCardinal: 7942,
                qAllValuesCardinal: -1,
              },
              qLibraryId: "14d98166-8e9d-46ba-974b-70fd83b29b91",
              title: "Product",
              cId: "bk09t9",
            },
          ],
          qMeasureInfo: [
            {
              qFallbackTitle: "Avg Lead Time",
              qApprMaxGlyphCount: 10,
              qCardinal: 0,
              qSortIndicator: "D",
              qNumFormat: {
                qType: "R",
                qnDec: 0,
                qUseThou: 0,
                qFmt: "########",
                qDec: ".",
                qThou: ",",
              },
              qMin: 0.5707829140985563,
              qMax: 19.278805673303264,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qLibraryId: "NJjjFj",
              qTrendLines: [],
              cId: "tpmb9l",
            },
          ],
          qEffectiveInterColumnSortOrder: [0],
          qGrandTotalRow: [],
          qDataPages: [],
          qPivotDataPages: [
            {
              qLeft: [
                {
                  qText: "                         ",
                  qElemNo: 234,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's American Beef Bologna",
                  qElemNo: 415,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's American Chicken Hot Dogs",
                  qElemNo: 2341,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's American Cole Slaw",
                  qElemNo: 3042,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's American Corned Beef",
                  qElemNo: 3752,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's American Foot-Long Hot Dogs",
                  qElemNo: 2278,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's American Low Fat Cole Slaw",
                  qElemNo: 7404,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's American Pimento Loaf",
                  qElemNo: 3039,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's American Potato Salad",
                  qElemNo: 1123,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's American Roasted Chicken",
                  qElemNo: 3538,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's American Sliced Chicken",
                  qElemNo: 6714,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's American Sliced Ham",
                  qElemNo: 4773,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's American Turkey Hot Dogs",
                  qElemNo: 2373,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's Applause Canned Peaches",
                  qElemNo: 1308,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's Atomic Bubble Gum",
                  qElemNo: 2746,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's Atomic Malted Milk Balls",
                  qElemNo: 1150,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's Atomic Mint Chocolate Bar",
                  qElemNo: 2134,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's Atomic Mints",
                  qElemNo: 4928,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's Atomic Semi-Sweet Chocolate Bar",
                  qElemNo: 2425,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's Atomic Spicy Mints",
                  qElemNo: 3824,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's Atomic Tasty Candy Bar",
                  qElemNo: 401,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's Atomic White Chocolate Bar",
                  qElemNo: 3330,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Apple Butter",
                  qElemNo: 1510,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Apple Jam",
                  qElemNo: 4452,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Apple Jelly",
                  qElemNo: 1680,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Apple Preserves",
                  qElemNo: 5429,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Brown Sugar",
                  qElemNo: 7488,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Canola Oil",
                  qElemNo: 3913,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Chunky Peanut Butter",
                  qElemNo: 225,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Columbian Coffee",
                  qElemNo: 5197,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Corn Oil",
                  qElemNo: 3625,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Creamy Peanut Butter",
                  qElemNo: 3269,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Decaf Coffee",
                  qElemNo: 6360,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Extra Chunky Peanut Butter",
                  qElemNo: 6651,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best French Roast Coffee",
                  qElemNo: 1665,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Grape Jam",
                  qElemNo: 2107,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Grape Jelly",
                  qElemNo: 3040,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Grape Preserves",
                  qElemNo: 452,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Hot Chocolate",
                  qElemNo: 6064,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Low Fat Apple Butter",
                  qElemNo: 3865,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Oregano",
                  qElemNo: 1255,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Pepper",
                  qElemNo: 3971,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Regular Coffee",
                  qElemNo: 7346,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Salt",
                  qElemNo: 4085,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Sesame Oil",
                  qElemNo: 4967,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Strawberry Jam",
                  qElemNo: 3363,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Strawberry Jelly",
                  qElemNo: 4291,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Strawberry Preserves",
                  qElemNo: 190,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Tomato Sauce",
                  qElemNo: 4412,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "Bill's BBB Best Vegetable Oil",
                  qElemNo: 1710,
                  qValue: "NaN",
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
              ],
              qTop: [
                {
                  qText: "Avg Lead Time",
                  qElemNo: 0,
                  qValue: "NaN",
                  qType: "P",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
              ],
              qData: [
                [
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                ],
                [
                  {
                    qText: "13.456309",
                    qNum: 13.456309165671744,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "7.68199",
                    qNum: 7.681990037157739,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "9.0293315",
                    qNum: 9.02933152381139,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "6.2188712",
                    qNum: 6.2188711787739495,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "12.907348",
                    qNum: 12.907347584327187,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "10.24103",
                    qNum: 10.24103020838966,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "8.7981899",
                    qNum: 8.798189872444322,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "9.4914286",
                    qNum: 9.491428594473858,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "7.9954815",
                    qNum: 7.995481483411954,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "10.478303",
                    qNum: 10.478302713850947,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "12.059461",
                    qNum: 12.059460996719064,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "13.51034",
                    qNum: 13.510340227222464,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "12.652777",
                    qNum: 12.652776890238446,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "8.8561446",
                    qNum: 8.856144587758957,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "12.664688",
                    qNum: 12.664688099507698,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "7.6359585",
                    qNum: 7.635958510519721,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "8.072912",
                    qNum: 8.072911967796616,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "11.408488",
                    qNum: 11.4084882609904,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "11.153078",
                    qNum: 11.153077596362053,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "9.5796206",
                    qNum: 9.579620586270208,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "9.7288153",
                    qNum: 9.7288152584476,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "7.9323103",
                    qNum: 7.932310341865436,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "6.6981795",
                    qNum: 6.698179530530542,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "9.5195495",
                    qNum: 9.51954949210661,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "11.645772",
                    qNum: 11.645771745559944,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "8.6687972",
                    qNum: 8.668797199988768,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "9.9421657",
                    qNum: 9.942165726846346,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "10.633664",
                    qNum: 10.633664214790397,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "12.727848",
                    qNum: 12.727847533484338,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "4.6031264",
                    qNum: 4.603126365249835,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "10.367439",
                    qNum: 10.36743930189077,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "8.9478655",
                    qNum: 8.94786545082135,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "4.7813503",
                    qNum: 4.781350314601703,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "10.594664",
                    qNum: 10.594663691287112,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "8.6309451",
                    qNum: 8.630945079900648,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "9.7903897",
                    qNum: 9.790389664435931,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "12.412626",
                    qNum: 12.412626117630227,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "8.3596523",
                    qNum: 8.359652328283701,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "10.405357",
                    qNum: 10.405357496948143,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "9.4413531",
                    qNum: 9.441353093758657,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "8.9046188",
                    qNum: 8.904618761939199,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "11.039368",
                    qNum: 11.039367535048456,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "10.796952",
                    qNum: 10.796952004343764,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "11.624126",
                    qNum: 11.624125653819094,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "11.784477",
                    qNum: 11.784476917300262,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "6.7661091",
                    qNum: 6.766109130680169,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "10.500563",
                    qNum: 10.500562563539674,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "11.42443",
                    qNum: 11.424429888905886,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "10.32113",
                    qNum: 10.321129770178732,
                    qType: "V",
                  },
                ],
              ],
              qArea: {
                qLeft: 0,
                qTop: 0,
                qWidth: 1,
                qHeight: 50,
              },
            },
          ],
          qStackedDataPages: [],
          qMode: "P",
          qNoOfLeftDims: 1,
          qTreeNodesOnDim: [],
          qColumnOrder: [],
        },
        title: "",
        subtitle: "",
        footnote: "",
        nullValueRepresentation: {
          text: "-",
        },
        components: [],
      },
      getEffectiveProperties: {
        qHyperCubeDef: {},
      },
    },
  ],
});
