version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:17.2

aliases:
  - &restore_yarn_cache
    name: Restore yarn cache
    keys:
      - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - yarn-packages-{{ .Branch }}
      - yarn-packages-
  - &save_yarn_cache
    name: Save yarn cache
    paths:
      - ~/.cache/yarn
    key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run: yarn install --frozen-lockfile
      - save_cache: *save_yarn_cache
      - store_artifacts:
          path: package.json
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Build
          command: yarn run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Lint
          command: yarn run lint

  unit-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Unit tests
          command: yarn run test:unit

  rendering-tests:
    <<: *defaults
    docker:
      - image: mcr.microsoft.com/playwright:focal
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Rendering tests
          command: yarn run test:rendering
      - store_artifacts:
          path: test/rendering/render.mjs-snapshots
      - store_artifacts:
          path: test/rendering/artifacts
      - store_artifacts:
          path: test/rendering/test-report

  types:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Types
          command: yarn run types:check

  spec:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Build API specification
          command: yarn run spec

workflows:
  version: 2
  build-all:
    jobs:
      - install
      - build:
          requires:
            - install
      - unit-tests:
          requires:
            - build
      - rendering-tests:
          requires:
            - build
      - lint:
          requires:
            - build
      - types:
          requires:
            - install
      - spec:
          requires:
            - install
