export default () => ({
  type: "sn-pivot-table",
  genericObjects: [
    {
      getLayout: {
        qInfo: {
          qId: "jgAJyu",
          qType: "sn-pivot-table",
        },
        qMeta: {
          privileges: ["read"],
        },
        qSelectionInfo: {},
        qHyperCube: {
          qSize: {
            qcx: 4,
            qcy: 1,
          },
          qDimensionInfo: [
            {
              qFallbackTitle: "Year",
              qApprMaxGlyphCount: 4,
              qCardinal: 2,
              qSortIndicator: "A",
              qGroupFallbackTitles: ["Year"],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 2,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ["$numeric", "$integer"],
              qDimensionType: "N",
              qGrouping: "N",
              qNumFormat: {
                qType: "I",
                qnDec: 0,
                qUseThou: 0,
                qFmt: "###0",
                qDec: ".",
                qThou: ",",
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ["Year"],
              qMin: 2006,
              qMax: 2007,
              qContinuousAxes: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 2,
                qHypercubeCardinal: 2,
                qAllValuesCardinal: -1,
              },
              qLibraryId: "7cd6768c-03dc-42d7-b6d0-02b6b25d38fd",
              title: "Year",
              autoSort: true,
              cId: "kvskHQt",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
            },
          ],
          qMeasureInfo: [
            {
              qFallbackTitle: "Avg Sales",
              qApprMaxGlyphCount: 9,
              qCardinal: 0,
              qSortIndicator: "D",
              qNumFormat: {
                qType: "R",
                qnDec: 0,
                qUseThou: 0,
                qFmt: "########",
                qDec: ".",
                qThou: ",",
              },
              qMin: 643.3088581607146,
              qMax: 931.0757322513505,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qLibraryId: "LvjWKp",
              qTrendLines: [],
              autoSort: true,
              cId: "stjQfQ",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
              quarantine: {
                qNumFormat: {},
                isCustomFormatted: false,
              },
            },
            {
              qFallbackTitle: "Actual Amount",
              qApprMaxGlyphCount: 11,
              qCardinal: 0,
              qSortIndicator: "D",
              qNumFormat: {
                qType: "U",
                qnDec: 0,
                qUseThou: 0,
              },
              qMin: 45731242.95,
              qMax: 46258458.110000014,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qLibraryId: "vDhvSum",
              qTrendLines: [],
              coloring: {},
              autoSort: true,
              cId: "TDsUJK",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
              quarantine: {
                qNumFormat: {},
                isCustomFormatted: false,
              },
            },
          ],
          qEffectiveInterColumnSortOrder: [-1, 0],
          qGrandTotalRow: [],
          qDataPages: [],
          qPivotDataPages: [
            {
              qLeft: [],
              qTop: [
                {
                  qText: "Avg Sales",
                  qElemNo: 0,
                  qValue: "NaN",
                  qType: "P",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [
                    {
                      qText: "2006",
                      qElemNo: 1,
                      qValue: 2006,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                    {
                      qText: "2007",
                      qElemNo: 0,
                      qValue: 2007,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                  ],
                },
                {
                  qText: "Actual Amount",
                  qElemNo: 1,
                  qValue: "NaN",
                  qType: "P",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [
                    {
                      qText: "2006",
                      qElemNo: 1,
                      qValue: 2006,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                    {
                      qText: "2007",
                      qElemNo: 0,
                      qValue: 2007,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [],
                    },
                  ],
                },
              ],
              qData: [
                [
                  {
                    qText: "643.30886",
                    qNum: 643.3088581607146,
                    qType: "V",
                  },
                  {
                    qText: "931.07573",
                    qNum: 931.0757322513505,
                    qType: "V",
                  },
                  {
                    qText: "45731242.95",
                    qNum: 45731242.95,
                    qType: "V",
                  },
                  {
                    qText: "46258458.11",
                    qNum: 46258458.110000014,
                    qType: "V",
                  },
                ],
              ],
              qArea: {
                qLeft: 0,
                qTop: 0,
                qWidth: 4,
                qHeight: 1,
              },
            },
          ],
          qStackedDataPages: [],
          qMode: "P",
          qNoOfLeftDims: 0,
          qTreeNodesOnDim: [],
          qColumnOrder: [],
        },
        search: {
          sorting: "auto",
        },
        showTitles: true,
        title: "",
        subtitle: "1 column, pseudo dim as first column",
        footnote: "",
        disableNavMenu: false,
        showDetails: true,
        showDetailsExpression: false,
        components: [],
        nullValueRepresentation: {
          text: "-",
        },
        visualization: "sn-pivot-table",
        version: "2.3.0",
        extensionMeta: {
          translationKey: "",
          icon: "puzzle",
          iconChar: "puzzle",
          isLibraryItem: true,
          visible: true,
          IconDefinition: {},
          name: "sn-pivot-table",
          description: "Pivot table supernova",
          template: "sn-pivot-table",
          iconPath:
            "M14.5,9 L13,9 L13,3.3 C13,3.1 12.9,3 12.7,3 L8,3 L8,1.5 C8,0.7 7.3,0 6.5,0 C5.7,0 5,0.7 5,1.5 L5,3 L0.3,3 C0.1,3 0,3.1 0,3.3 L0,9 L1.5,9 C2.3,9 3,9.7 3,10.5 C3,11.3 2.3,12 1.5,12 L0,12 L0,15.7 C0,15.9 0.1,16 0.3,16 L5,16 L5,14.5 C5,13.7 5.7,13 6.5,13 C7.3,13 8,13.7 8,14.5 L8,16 L12.7,16 C12.9,16 13,15.9 13,15.7 L13,12 L14.5,12 C15.3,12 16,11.3 16,10.5 C16,9.7 15.3,9 14.5,9 Z",
          isThirdParty: true,
          id: "rmQctFcQtWrx-gPyk6gzUvfnphijKOxY",
          tenantId: "So2tYBBh-SeC2uqq2ghwvPxTRS9ca45i",
          userId: "Tc_Xcu0ACCRJHvXCacSY0_VWrOZIqP0C",
          type: "visualization",
          qextFilename: "sn-pivot-table",
          qextVersion: "2.4.0",
          loadpath: "sn-pivot-table",
          version: "56.0.0",
          author: "QlikTech International AB",
          tags: [],
          checksum: null,
          bundled: false,
          supernova: true,
          file: {
            contentType: "application/zip",
            contentLength: 1252280,
            md5: "0cfe6bc70ecb73fed6e32eae923b973d",
            fileId: "fZgQ8eKieiuvW6LXsXhjMMgHRRn_M4xP",
            originalname: "sn-pivot-table-ext.zip",
          },
          createdAt: "2023-10-06T12:44:39.924Z",
          updatedAt: "2023-11-16T10:07:02.333Z",
          cloud: true,
        },
        appId: "1aac3e7b-5681-43c3-8516-8269ba82c0d2",
      },
      getEffectiveProperties: {
        qHyperCubeDef: {},
      },
    },
  ],
});
