export default () => ({
  type: "sn-pivot-table",
  genericObjects: [
    {
      getLayout: {
        qInfo: {
          qId: "SJWwDu",
          qType: "sn-pivot-table",
        },
        qMeta: {
          privileges: ["read"],
        },
        qSelectionInfo: {},
        qHyperCube: {
          qSize: {
            qcx: 38,
            qcy: 2,
          },
          qDimensionInfo: [
            {
              qFallbackTitle: "Year",
              qApprMaxGlyphCount: 4,
              qCardinal: 2,
              qSortIndicator: "A",
              qGroupFallbackTitles: ["Year"],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 2,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ["$numeric", "$integer"],
              qDimensionType: "N",
              qGrouping: "N",
              qNumFormat: {
                qType: "I",
                qnDec: 0,
                qUseThou: 0,
                qFmt: "###0",
                qDec: ".",
                qThou: ",",
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ["Year"],
              qMin: 2006,
              qMax: 2007,
              qContinuousAxes: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 2,
                qHypercubeCardinal: 2,
                qAllValuesCardinal: -1,
              },
              qLibraryId: "7cd6768c-03dc-42d7-b6d0-02b6b25d38fd",
              title: "Year",
              autoSort: true,
              cId: "kvskHQt",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
            },
            {
              qFallbackTitle: "Month",
              qApprMaxGlyphCount: 3,
              qCardinal: 12,
              qSortIndicator: "A",
              qGroupFallbackTitles: ["Month"],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 12,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ["$numeric", "$integer"],
              qDimensionType: "N",
              qGrouping: "N",
              qNumFormat: {
                qType: "U",
                qnDec: 0,
                qUseThou: 0,
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ["Month"],
              qMin: "NaN",
              qMax: "NaN",
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 12,
                qHypercubeCardinal: 18,
                qAllValuesCardinal: -1,
              },
              qLibraryId: "KHvcSGE",
              title: "Month",
              autoSort: true,
              cId: "arNRFP",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
            },
            {
              qFallbackTitle: "Product Group",
              qApprMaxGlyphCount: 19,
              qCardinal: 17,
              qSortIndicator: "A",
              qGroupFallbackTitles: ["Product Group"],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 17,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ["$ascii", "$text"],
              qDimensionType: "D",
              qGrouping: "N",
              qNumFormat: {
                qType: "U",
                qnDec: 0,
                qUseThou: 0,
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ["Product Group Desc"],
              qMin: "NaN",
              qMax: "NaN",
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 17,
                qHypercubeCardinal: 3,
                qAllValuesCardinal: -1,
              },
              qLibraryId: "2d0c76e0-f6f6-4dc4-8d9f-55dae429742d",
              title: "Product Group",
              autoSort: true,
              cId: "RugWuf",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
            },
            {
              qFallbackTitle: "Product Sub Group",
              qApprMaxGlyphCount: 17,
              qCardinal: 70,
              qSortIndicator: "A",
              qGroupFallbackTitles: ["Product Sub Group"],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 70,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ["$ascii", "$text"],
              qDimensionType: "D",
              qGrouping: "N",
              qNumFormat: {
                qType: "U",
                qnDec: 0,
                qUseThou: 0,
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ["Product Sub Group Desc"],
              qMin: "NaN",
              qMax: "NaN",
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 70,
                qHypercubeCardinal: 0,
                qAllValuesCardinal: -1,
              },
              qLibraryId: "e1432d2b-be66-4e9f-a134-65327550e346",
              title: "Product Sub Group",
              autoSort: true,
              cId: "bxFY",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
            },
          ],
          qMeasureInfo: [
            {
              qFallbackTitle: "Avg Sales",
              qApprMaxGlyphCount: 9,
              qCardinal: 0,
              qSortIndicator: "D",
              qNumFormat: {
                qType: "R",
                qnDec: 0,
                qUseThou: 0,
                qFmt: "########",
                qDec: ".",
                qThou: ",",
              },
              qMin: 84.29316195372745,
              qMax: 2056.989870751558,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qLibraryId: "LvjWKp",
              qTrendLines: [],
              autoSort: true,
              cId: "stjQfQ",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
              quarantine: {
                qNumFormat: {},
                isCustomFormatted: false,
              },
            },
            {
              qFallbackTitle: "Actual Amount",
              qApprMaxGlyphCount: 12,
              qCardinal: 0,
              qSortIndicator: "D",
              qNumFormat: {
                qType: "U",
                qnDec: 0,
                qUseThou: 0,
              },
              qMin: 53291.89,
              qMax: 274705242.0199997,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qLibraryId: "vDhvSum",
              qTrendLines: [],
              coloring: {},
              autoSort: true,
              cId: "TDsUJK",
              columnWidth: {
                type: "auto",
                pixels: 200,
                percentage: 20,
              },
              quarantine: {
                qNumFormat: {},
                isCustomFormatted: false,
              },
            },
          ],
          qEffectiveInterColumnSortOrder: [0, 1, -1, 2, 3],
          qGrandTotalRow: [],
          qDataPages: [],
          qPivotDataPages: [
            {
              qLeft: [
                {
                  qText: "2006",
                  qElemNo: 1,
                  qValue: 2006,
                  qCanExpand: true,
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
                {
                  qText: "2007",
                  qElemNo: 0,
                  qValue: 2007,
                  qCanExpand: true,
                  qType: "N",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [],
                },
              ],
              qTop: [
                {
                  qText: "Avg Sales",
                  qElemNo: 0,
                  qValue: "NaN",
                  qType: "P",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [
                    {
                      qText: "-",
                      qElemNo: -2,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "U",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Alcoholic Beverages",
                      qElemNo: 0,
                      qValue: "NaN",
                      qCanCollapse: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qText: "Beer",
                          qElemNo: 33,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                        {
                          qText: "Wine",
                          qElemNo: 34,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Baked Goods",
                      qElemNo: 1,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Baking Goods",
                      qElemNo: 12,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Beverages",
                      qElemNo: 2,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Breakfast Foods",
                      qElemNo: 3,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Canned Foods",
                      qElemNo: 4,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Canned Products",
                      qElemNo: 13,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Dairy",
                      qElemNo: 5,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Deli",
                      qElemNo: 6,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Eggs",
                      qElemNo: 14,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Frozen Foods",
                      qElemNo: 15,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Meat",
                      qElemNo: 7,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Produce",
                      qElemNo: 8,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Seafood",
                      qElemNo: 9,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Snack Foods",
                      qElemNo: 10,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Snacks",
                      qElemNo: 11,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Starchy Foods",
                      qElemNo: 16,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  qText: "Actual Amount",
                  qElemNo: 1,
                  qValue: "NaN",
                  qType: "P",
                  qUp: 0,
                  qDown: 0,
                  qSubNodes: [
                    {
                      qText: "-",
                      qElemNo: -2,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "U",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Alcoholic Beverages",
                      qElemNo: 0,
                      qValue: "NaN",
                      qCanCollapse: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qText: "Beer",
                          qElemNo: 33,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                        {
                          qText: "Wine",
                          qElemNo: 34,
                          qValue: "NaN",
                          qType: "N",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Baked Goods",
                      qElemNo: 1,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Baking Goods",
                      qElemNo: 12,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Beverages",
                      qElemNo: 2,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Breakfast Foods",
                      qElemNo: 3,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Canned Foods",
                      qElemNo: 4,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Canned Products",
                      qElemNo: 13,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Dairy",
                      qElemNo: 5,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Deli",
                      qElemNo: 6,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Eggs",
                      qElemNo: 14,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Frozen Foods",
                      qElemNo: 15,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Meat",
                      qElemNo: 7,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Produce",
                      qElemNo: 8,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Seafood",
                      qElemNo: 9,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Snack Foods",
                      qElemNo: 10,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Snacks",
                      qElemNo: 11,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                    {
                      qText: "Starchy Foods",
                      qElemNo: 16,
                      qValue: "NaN",
                      qCanExpand: true,
                      qType: "N",
                      qUp: 0,
                      qDown: 0,
                      qSubNodes: [
                        {
                          qElemNo: -4,
                          qValue: "NaN",
                          qType: "E",
                          qUp: 0,
                          qDown: 0,
                          qSubNodes: [],
                        },
                      ],
                    },
                  ],
                },
              ],
              qData: [
                [
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "269.14829",
                    qNum: 269.1482853025936,
                    qType: "V",
                  },
                  {
                    qText: "955.56893",
                    qNum: 955.5689304461938,
                    qType: "V",
                  },
                  {
                    qText: "176.17208",
                    qNum: 176.1720786516853,
                    qType: "V",
                  },
                  {
                    qText: "566.81297",
                    qNum: 566.8129733887097,
                    qType: "V",
                  },
                  {
                    qText: "657.96416",
                    qNum: 657.9641589523595,
                    qType: "V",
                  },
                  {
                    qText: "502.48339",
                    qNum: 502.48338582677155,
                    qType: "V",
                  },
                  {
                    qText: "504.90818",
                    qNum: 504.90818423597716,
                    qType: "V",
                  },
                  {
                    qText: "443.93759",
                    qNum: 443.93758754863813,
                    qType: "V",
                  },
                  {
                    qText: "445.37216",
                    qNum: 445.37215674806333,
                    qType: "V",
                  },
                  {
                    qText: "1465.9811",
                    qNum: 1465.9811289147851,
                    qType: "V",
                  },
                  {
                    qText: "122.94226",
                    qNum: 122.94226315789486,
                    qType: "V",
                  },
                  {
                    qText: "798.62755",
                    qNum: 798.6275519102988,
                    qType: "V",
                  },
                  {
                    qText: "231.7759",
                    qNum: 231.77589958159,
                    qType: "V",
                  },
                  {
                    qText: "692.93311",
                    qNum: 692.933109136247,
                    qType: "V",
                  },
                  {
                    qText: "84.293162",
                    qNum: 84.29316195372745,
                    qType: "V",
                  },
                  {
                    qText: "362.66315",
                    qNum: 362.6631456548346,
                    qType: "V",
                  },
                  {
                    qText: "389.00698",
                    qNum: 389.00698209718627,
                    qType: "V",
                  },
                  {
                    qText: "1081.0451",
                    qNum: 1081.0450712530687,
                    qType: "V",
                  },
                  {
                    qText: "53291.89",
                    qNum: 53291.89,
                    qType: "V",
                  },
                  {
                    qText: "12192121.77",
                    qNum: 12192121.770000014,
                    qType: "V",
                  },
                  {
                    qText: "21175582.16",
                    qNum: 21175582.15999996,
                    qType: "V",
                  },
                  {
                    qText: "28049724",
                    qNum: 28049724.000000026,
                    qType: "V",
                  },
                  {
                    qText: "128919842.52",
                    qNum: 128919842.51999994,
                    qType: "V",
                  },
                  {
                    qText: "65811791.22",
                    qNum: 65811791.22000004,
                    qType: "V",
                  },
                  {
                    qText: "18328287.31",
                    qNum: 18328287.309999973,
                    qType: "V",
                  },
                  {
                    qText: "146707989.47",
                    qNum: 146707989.46999994,
                    qType: "V",
                  },
                  {
                    qText: "13288353.78",
                    qNum: 13288353.780000016,
                    qType: "V",
                  },
                  {
                    qText: "77367375.02",
                    qNum: 77367375.02000001,
                    qType: "V",
                  },
                  {
                    qText: "96945625.29",
                    qNum: 96945625.28999993,
                    qType: "V",
                  },
                  {
                    qText: "18225752.86",
                    qNum: 18225752.85999998,
                    qType: "V",
                  },
                  {
                    qText: "179210995.45",
                    qNum: 179210995.44999987,
                    qType: "V",
                  },
                  {
                    qText: "5978428.53",
                    qNum: 5978428.529999999,
                    qType: "V",
                  },
                  {
                    qText: "134628042.3",
                    qNum: 134628042.29999986,
                    qType: "V",
                  },
                  {
                    qText: "35279409.25",
                    qNum: 35279409.25000001,
                    qType: "V",
                  },
                  {
                    qText: "214737170.47",
                    qNum: 214737170.4699997,
                    qType: "V",
                  },
                  {
                    qText: "45495681.97",
                    qNum: 45495681.97,
                    qType: "V",
                  },
                  {
                    qText: "29860074.03",
                    qNum: 29860074.03000002,
                    qType: "V",
                  },
                ],
                [
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "478.67935",
                    qNum: 478.6793467336685,
                    qType: "V",
                  },
                  {
                    qText: "1423.2052",
                    qNum: 1423.2051882845171,
                    qType: "V",
                  },
                  {
                    qText: "219.85178",
                    qNum: 219.8517776298268,
                    qType: "V",
                  },
                  {
                    qText: "1015.2858",
                    qNum: 1015.2858052256526,
                    qType: "V",
                  },
                  {
                    qText: "1420.8924",
                    qNum: 1420.8923722883148,
                    qType: "V",
                  },
                  {
                    qText: "619.00534",
                    qNum: 619.005340393343,
                    qType: "V",
                  },
                  {
                    qText: "634.62527",
                    qNum: 634.6252728400162,
                    qType: "V",
                  },
                  {
                    qText: "96.734573",
                    qNum: 96.73457317073168,
                    qType: "V",
                  },
                  {
                    qText: "816.6702",
                    qNum: 816.670201722018,
                    qType: "V",
                  },
                  {
                    qText: "2056.9899",
                    qNum: 2056.989870751558,
                    qType: "V",
                  },
                  {
                    qText: "172.43043",
                    qNum: 172.43042929292946,
                    qType: "V",
                  },
                  {
                    qText: "848.55317",
                    qNum: 848.5531652360515,
                    qType: "V",
                  },
                  {
                    qText: "382.98118",
                    qNum: 382.9811818181817,
                    qType: "V",
                  },
                  {
                    qText: "1074.999",
                    qNum: 1074.9989943892972,
                    qType: "V",
                  },
                  {
                    qText: "108.61213",
                    qNum: 108.61212962962966,
                    qType: "V",
                  },
                  {
                    qText: "423.98752",
                    qNum: 423.9875220541904,
                    qType: "V",
                  },
                  {
                    qText: "417.82772",
                    qNum: 417.8277169663805,
                    qType: "V",
                  },
                  {
                    qText: "1404.6198",
                    qNum: 1404.6197580645153,
                    qType: "V",
                  },
                  {
                    qText: "-",
                    qNum: "NaN",
                    qType: "U",
                  },
                  {
                    qText: "20173793.31",
                    qNum: 20173793.30999999,
                    qType: "V",
                  },
                  {
                    qText: "25520224.82",
                    qNum: 25520224.819999956,
                    qType: "V",
                  },
                  {
                    qText: "70130367.24",
                    qNum: 70130367.23999995,
                    qType: "V",
                  },
                  {
                    qText: "236550279.61",
                    qNum: 236550279.60999966,
                    qType: "V",
                  },
                  {
                    qText: "144263974.3",
                    qNum: 144263974.29999983,
                    qType: "V",
                  },
                  {
                    qText: "37245289.39",
                    qNum: 37245289.38999996,
                    qType: "V",
                  },
                  {
                    qText: "167794633.54",
                    qNum: 167794633.5399999,
                    qType: "V",
                  },
                  {
                    qText: "19078812.68",
                    qNum: 19078812.68,
                    qType: "V",
                  },
                  {
                    qText: "113788224.45",
                    qNum: 113788224.44999994,
                    qType: "V",
                  },
                  {
                    qText: "120932518.5",
                    qNum: 120932518.49999982,
                    qType: "V",
                  },
                  {
                    qText: "34091306.95",
                    qNum: 34091306.94999991,
                    qType: "V",
                  },
                  {
                    qText: "274705242.02",
                    qNum: 274705242.0199997,
                    qType: "V",
                  },
                  {
                    qText: "9227411.16",
                    qNum: 9227411.16000001,
                    qType: "V",
                  },
                  {
                    qText: "126480177.96",
                    qNum: 126480177.95999977,
                    qType: "V",
                  },
                  {
                    qText: "16872831.15",
                    qNum: 16872831.15,
                    qType: "V",
                  },
                  {
                    qText: "225845955.26",
                    qNum: 225845955.25999966,
                    qType: "V",
                  },
                  {
                    qText: "51163783.52",
                    qNum: 51163783.51999999,
                    qType: "V",
                  },
                  {
                    qText: "51275758.22",
                    qNum: 51275758.219999924,
                    qType: "V",
                  },
                ],
              ],
              qArea: {
                qLeft: 0,
                qTop: 0,
                qWidth: 38,
                qHeight: 2,
              },
            },
          ],
          qStackedDataPages: [],
          qMode: "P",
          qNoOfLeftDims: 2,
          qTreeNodesOnDim: [],
          qColumnOrder: [],
        },
        search: {
          sorting: "auto",
        },
        showTitles: true,
        title: "",
        subtitle: "2 row, 2 columns, pseudo dim as first column. Expanded cells",
        footnote: "",
        disableNavMenu: false,
        showDetails: true,
        showDetailsExpression: false,
        components: [],
        nullValueRepresentation: {
          text: "-",
        },
        visualization: "sn-pivot-table",
        version: "2.3.0",
        extensionMeta: {
          translationKey: "",
          icon: "puzzle",
          iconChar: "puzzle",
          isLibraryItem: true,
          visible: true,
          IconDefinition: {},
          name: "sn-pivot-table",
          description: "Pivot table supernova",
          template: "sn-pivot-table",
          iconPath:
            "M14.5,9 L13,9 L13,3.3 C13,3.1 12.9,3 12.7,3 L8,3 L8,1.5 C8,0.7 7.3,0 6.5,0 C5.7,0 5,0.7 5,1.5 L5,3 L0.3,3 C0.1,3 0,3.1 0,3.3 L0,9 L1.5,9 C2.3,9 3,9.7 3,10.5 C3,11.3 2.3,12 1.5,12 L0,12 L0,15.7 C0,15.9 0.1,16 0.3,16 L5,16 L5,14.5 C5,13.7 5.7,13 6.5,13 C7.3,13 8,13.7 8,14.5 L8,16 L12.7,16 C12.9,16 13,15.9 13,15.7 L13,12 L14.5,12 C15.3,12 16,11.3 16,10.5 C16,9.7 15.3,9 14.5,9 Z",
          isThirdParty: true,
          id: "rmQctFcQtWrx-gPyk6gzUvfnphijKOxY",
          tenantId: "So2tYBBh-SeC2uqq2ghwvPxTRS9ca45i",
          userId: "Tc_Xcu0ACCRJHvXCacSY0_VWrOZIqP0C",
          type: "visualization",
          qextFilename: "sn-pivot-table",
          qextVersion: "2.4.0",
          loadpath: "sn-pivot-table",
          version: "56.0.0",
          author: "QlikTech International AB",
          tags: [],
          checksum: null,
          bundled: false,
          supernova: true,
          file: {
            contentType: "application/zip",
            contentLength: 1252280,
            md5: "0cfe6bc70ecb73fed6e32eae923b973d",
            fileId: "fZgQ8eKieiuvW6LXsXhjMMgHRRn_M4xP",
            originalname: "sn-pivot-table-ext.zip",
          },
          createdAt: "2023-10-06T12:44:39.924Z",
          updatedAt: "2023-11-16T10:07:02.333Z",
          cloud: true,
        },
        appId: "1aac3e7b-5681-43c3-8516-8269ba82c0d2",
      },
      getEffectiveProperties: {
        qHyperCubeDef: {},
      },
    },
  ],
});
