name: Build
on:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        required: true
        default: false
  pull_request:
    branches:
      - main
      - alpha
  push:
    branches:
      - main
      - alpha

jobs:
  build:
    uses: qlik-oss/sn-gh-workflows/.github/workflows/build.yaml@v1
    secrets: inherit
    with:
      release: ${{ inputs.release || false}}
      release_branches: |
        [
          'main',
          {
            name: 'alpha',
            prerelease: true
          }
        ]
