name: Build
on:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        required: true
        default: false
  pull_request:
    branches:
      - main
      - alpha
  push:
    branches:
      - main
      - alpha

jobs:
  build:
    uses: qlik-oss/sn-gh-workflows/.github/workflows/build.yaml@v2
    secrets: inherit
    with:
      release: ${{ inputs.release || false}}
      api_specification_path: api-specifications/properties.json
      package_manager: pnpm

  locale:
    runs-on: ubuntu-latest
    steps:
      - name: Setup workspace
        uses: qlik-oss/sn-gh-workflows/actions/setup@v2
        with:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          package_manager: pnpm

      - name: Generate locale
        run: pnpm run locale:generate

      - name: Verify locale
        run: pnpm run locale:verify
